### ISSUE TITLE
MEF IODataEndpoint should support GUID and have the loading mechanism defined inside the Package

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Web.Utilities#2]
Currently the actual loading of MEF endpoints is done inside the code of the application. However this should be external in the Utilities package.

Furtermore the plugin should support a GUID property and a mechanism to override the Priority.

See [Overriding MEF Metadata](http://blogs.msdn.com/b/dsplaisted/archive/2010/04/01/overriding-mef-metadata.aspx) for details.

**Comment by dfch** [comment]
@rufer7 why would we want that (loading it in the Utilities package)? I currenty do not get it, pls give me a hint

**Comment by rufer7** [comment]
@dfch I moved this issue from System.Utilities to Web.Utilities. I could imagine that the idea behind would be having the MEF resolver logic in one place like Web.Utilities!?

**Comment by dfch** [comment]
ok for me

**Comment by rufer7** [comment]
@dfch we decided to use StructureMap for plugin loading mechanism and injection. StructureMap will then be configured per project so this task is not necessary anymore. I'll close it.
